### Series

- A Series is a one-dimensional labeled array. Think of it as a single column of data, where every value has an associated index.

In [1]:
import pandas as pd
marks = pd.Series([85, 79, 90, 54])
print(marks)

0    85
1    79
2    90
3    54
dtype: int64

In [4]:
# custom indexes

marks = pd.Series(
    [86, 90, 70],
    index= ['Physics', 'Math', 'Chemistry'],
    name= 'Student Marks'
)
print(marks)
print()
print(marks['Math'])

Physics      86
Math         90
Chemistry    70
Name: Student Marks, dtype: int64

90

In [5]:
# Series from list
country = ['India', 'Pakistan', 'USA', 'Nepal', 'Turkey']
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4      Turkey
dtype: str

In [6]:
# Series from dict
marks = {
    'maths' : 67,
    'english' : 57,
    'science' : 100,
    'urdu' : 77
}
marks_series = pd.Series(marks, name="Fateh's Result")
marks_series

maths       67
english     57
science    100
urdu        77
Name: Fateh's Result, dtype: int64

### DataFrame

- A DataFrame is a two-dimensional labeled data structure consisting of rows and columns, similar to an Excel table or SQL table.

In [ ]:
# It can be created by dict and list a well
data = {
    "Name" : ["Fateh", "Ali", "Asad", "Zain"],
    "Age" : [20, 30, 21, 24],
    "Marks": [85, 92, 76, 88],
    "City" : ["Lahore", "Karachi", "Islamabd", "Multan"]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks      City
0  Fateh   20     85    Lahore
1    Ali   30     92   Karachi
2   Asad   21     76  Islamabd
3   Zain   24     88    Multan

### DataFrame Methods and Attributes

In [ ]:
df.shape # No. of rows and columns

(4, 4)

In [10]:
df.size # No. of elements

16

In [11]:
df.columns # Names of columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='str')

In [12]:
df.dtypes # data types of each column

Name       str
Age      int64
Marks    int64
City       str
dtype: object

In [13]:
df.head(2) # Display top n number of rows

    Name  Age  Marks     City
0  Fateh   20     85   Lahore
1    Ali   30     92  Karachi

In [14]:
df.tail(2) # Display bottom n number of rows

   Name  Age  Marks      City
2  Asad   21     76  Islamabd
3  Zain   24     88    Multan

In [ ]:
df.info() # Column information, null counts and types

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
 3   City    4 non-null      str
dtypes: int64(2), str(2)
memory usage: 303.0 bytes

In [16]:
df.describe() # Summary of numerical columns

         Age      Marks
count   4.00   4.000000
mean   23.75  85.250000
std     4.50   6.800735
min    20.00  76.000000
25%    20.75  82.750000
50%    22.50  86.500000
75%    25.50  89.000000
max    30.00  92.000000

### Selecting Columns

In [ ]:
# single column
df['Name'] # Gives a Series

0    Fateh
1      Ali
2     Asad
3     Zain
Name: Name, dtype: str

In [ ]:
# multiple column
df[['Name', 'Marks']] # give a DataFrame

    Name  Marks
0  Fateh     85
1    Ali     92
2   Asad     76
3   Zain     88

### Row Indexing

In [ ]:
# loc selects data using row and column labels.
# With loc, label-based slices include the ending label when present.
df.loc[1]

Name         Ali
Age           30
Marks         92
City     Karachi
Name: 1, dtype: object

In [22]:
df.loc[1,'Name']

'Ali'

In [23]:
df.loc[0:2, 'Name']

0    Fateh
1      Ali
2     Asad
Name: Name, dtype: str

In [24]:
df.loc[:, ['Name', 'Age']]

    Name  Age
0  Fateh   20
1    Ali   30
2   Asad   21
3   Zain   24

In [25]:
# iloc selects data using integer positions.
# With iloc, the ending position is excluded, just like ordinary Python slicing.

df.iloc[1]

Name         Ali
Age           30
Marks         92
City     Karachi
Name: 1, dtype: object

In [26]:
df.iloc[1,0]

'Ali'

In [27]:
df.iloc[0:2]

    Name  Age  Marks     City
0  Fateh   20     85   Lahore
1    Ali   30     92  Karachi

In [28]:
df.iloc[:, 0:2]

    Name  Age
0  Fateh   20
1    Ali   30
2   Asad   21
3   Zain   24